// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sliding_motif_score
Rcpp::List sliding_motif_score(Rcpp::NumericMatrix matrix, unsigned int matlen, const double scoremax, const std::vector<std::string> sequences);
RcppExport SEXP _motifscanR_sliding_motif_score(SEXP matrixSEXP, SEXP matlenSEXP, SEXP scoremaxSEXP, SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type matlen(matlenSEXP);
    Rcpp::traits::input_parameter< const double >::type scoremax(scoremaxSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(sliding_motif_score(matrix, matlen, scoremax, sequences));
    return rcpp_result_gen;
END_RCPP
}
// motif_score
std::vector<double> motif_score(Rcpp::NumericMatrix matrix, unsigned int matlen, const double scoremax, const std::vector<std::string> sequences);
RcppExport SEXP _motifscanR_motif_score(SEXP matrixSEXP, SEXP matlenSEXP, SEXP scoremaxSEXP, SEXP sequencesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type matlen(matlenSEXP);
    Rcpp::traits::input_parameter< const double >::type scoremax(scoremaxSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type sequences(sequencesSEXP);
    rcpp_result_gen = Rcpp::wrap(motif_score(matrix, matlen, scoremax, sequences));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_motifscanR_sliding_motif_score", (DL_FUNC) &_motifscanR_sliding_motif_score, 4},
    {"_motifscanR_motif_score", (DL_FUNC) &_motifscanR_motif_score, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_motifscanR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
