# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sliding_motif_score <- function(matrix, matlen, scoremax, sequences) {
    .Call(`_motifscanR_sliding_motif_score`, matrix, matlen, scoremax, sequences)
}

motif_score <- function(matrix, matlen, scoremax, sequences) {
    .Call(`_motifscanR_motif_score`, matrix, matlen, scoremax, sequences)
}

